### ISSUE TITLE
Possible security vulnerability with this code

### ISSUE THREAD

**Issue by jw35** [danielrichman/python-raven#7]
It is possible (I'm not skilled enough to tell) that this code suffers from a security vulnerability recently discovered in other Ucam webAuth ('Raven') implimentations. Further details here:

https://wiki.cam.ac.uk/raven/March_2015_security_vulnerability

Jon Warbrick, Aven Support, University of Cambridge. raven-support@ucs.cam.ac.uk

**Comment by danielrichman** [comment]
I don't believe so: acceptable public keys are explicitly named and loaded once at startup

https://github.com/danielrichman/python-raven/blob/master/raven/__init__.py#L103

and kept in a dictionary. If the server supplies a `kid` not in this list, it simply rejects it

https://github.com/danielrichman/python-raven/blob/master/ucam_webauth/__init__.py#L687.

**Comment by danielrichman** [comment]
I don't believe so: acceptable public keys are explicitly named and loaded once at startup

https://github.com/danielrichman/python-raven/blob/master/raven/__init__.py#L103

and kept in a dictionary. If the server supplies a `kid` not in this list, it simply rejects it

https://github.com/danielrichman/python-raven/blob/master/ucam_webauth/__init__.py#L687.

Thank you for the report!

**Comment by danielrichman** [comment]
(It is worth noting that https://github.com/danielrichman/python-raven/blob/master/raven/__init__.py#L64 is basically textbook-vulnerable to this problem, but that function is only used to statically load keys at startup and is never invoked with user supplied arguments).

**Comment by jw35** [comment]
Yes, that all looks OK - thanks for the confirmation. In the time I had available I really couldn't find the necessary code!
